language: python
python:
  - "2.7"
  - "3.3"
install:
  - pip install -r requirements.txt
script:
  - python scraper.py 2
cache:
  pip: true
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

notifications:
  email:
    on_success: change
    on_failure: always
